/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация пользователя */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Авторизация пользователя */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновление токенов */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход пользователя - удалиение токенов и очищение куки */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение информации о текущем пользователе */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload a new profile avatar */
        put: operations["AuthController_updateAvatar"];
        post?: never;
        /** Reset profile avatar to the default */
        delete: operations["AuthController_resetAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/ws-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить короткоживущий токен для WebSocket */
        get: operations["AuthController_wsToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить активные сессии пользователя */
        get: operations["AuthController_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Завершить активную сессию */
        delete: operations["AuthController_revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/avatars/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a locally stored avatar */
        get: operations["StorageController_avatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces available to the current user */
        get: operations["WorkspacesController_findAll"];
        put?: never;
        /** Create a workspace */
        post: operations["WorkspacesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the active workspace */
        put: operations["WorkspacesController_switchActive"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspace members */
        get: operations["WorkspacesController_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}/members/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a workspace member role */
        patch: operations["WorkspacesController_updateMemberRole"];
        trace?: never;
    };
    "/api/workspaces/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a workspace member */
        delete: operations["WorkspacesController_removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a workspace */
        delete: operations["WorkspacesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active workspace invite links */
        get: operations["WorkspaceInvitesController_list"];
        put?: never;
        /** Create a public workspace invite link */
        post: operations["WorkspaceInvitesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a workspace invite link */
        delete: operations["WorkspaceInvitesController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace-invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview a public workspace invite */
        get: operations["WorkspaceInvitesController_preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace-invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a public workspace invite */
        post: operations["WorkspaceInvitesController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все доски авторизованного пользователя */
        get: operations["BoardsController_findAll"];
        put?: never;
        /** Создать доску */
        post: operations["BoardsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверить доступ к доске */
        get: operations["BoardsController_checkAccess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved board views */
        get: operations["BoardsController_views"];
        put?: never;
        /** Create a saved board view */
        post: operations["BoardsController_createView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/views/{viewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a saved board view */
        delete: operations["BoardsController_deleteView"];
        options?: never;
        head?: never;
        /** Update a saved board view */
        patch: operations["BoardsController_updateView"];
        trace?: never;
    };
    "/api/boards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить доску по id */
        get: operations["BoardsController_findOne"];
        /** Обновить доску */
        put: operations["BoardsController_update"];
        post?: never;
        /** Удалить доску */
        delete: operations["BoardsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Пригласить пользователя к доске */
        post: operations["BoardsController_share"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список участников доски */
        get: operations["BoardsController_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/members/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a board member role */
        patch: operations["BoardsController_updateMemberRole"];
        trace?: never;
    };
    "/api/boards/{id}/share/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить участника из доски */
        delete: operations["BoardsController_revokeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspace teams */
        get: operations["TeamsController_list"];
        put?: never;
        /** Create a workspace team */
        post: operations["TeamsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/teams/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams of the current user */
        get: operations["TeamsController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/teams/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a workspace team */
        get: operations["TeamsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a workspace team */
        delete: operations["TeamsController_remove"];
        options?: never;
        head?: never;
        /** Update a workspace team */
        patch: operations["TeamsController_update"];
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/teams/{teamId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List team members */
        get: operations["TeamsController_listMembers"];
        put?: never;
        /** Add a workspace member to a team */
        post: operations["TeamsController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/teams/{teamId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from a team */
        delete: operations["TeamsController_removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/teams/{teamId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accessible tasks assigned to a team */
        get: operations["TeamsController_listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/demo-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open the showcase demo workspace */
        post: operations["DemoController_demoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/workspace/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset the current demo workspace */
        post: operations["DemoController_resetWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/workspace-invites/{token}/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a temporary account for a demo invite */
        post: operations["DemoController_registerFromDemoInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создание колонки */
        post: operations["ColumnsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/columns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update column title/order */
        put: operations["ColumnsController_update"];
        post?: never;
        /** Delete column (cascades tasks) */
        delete: operations["ColumnsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/columns/board/{boardId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder columns in board */
        put: operations["ColumnsController_reorder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать задачу в колонке */
        post: operations["TasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить задачу */
        put: operations["TasksController_update"];
        post?: never;
        /** Удалить задачу */
        delete: operations["TasksController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Переместить задачу в другую колонку (drag & drop) */
        patch: operations["TasksController_move"];
        trace?: never;
    };
    "/api/tasks/column/{columnId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Переупорядочить задачи в колонке */
        put: operations["TasksController_reorder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/analytics/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статистика выполненных задач по дням */
        get: operations["TasksController_analyticsDaily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/analytics/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статистика выполненных задач по неделям */
        get: operations["TasksController_analyticsWeekly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/analytics/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статистика выполненных задач по месяцам */
        get: operations["TasksController_analyticsMonthly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводка по выполнению задач в срок и с опозданием */
        get: operations["TasksController_analyticsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequestDto: {
            /** @example john@example.com */
            email: string;
            /** @example John Doe */
            name: string;
            /** @example password123 */
            password: string;
            /**
             * Format: binary
             * @description Optional PNG, JPEG, or WebP avatar up to 2 MB
             */
            avatar?: string;
        };
        UserDto: {
            id: string;
            email: string;
            name: string;
            avatar?: string;
            activeWorkspaceId?: string | null;
        };
        AuthResponseDto: {
            user: components["schemas"]["UserDto"];
        };
        LoginDto: {
            /** @example john@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        MessageDto: {
            /** @example Успешный ответ */
            message: string;
        };
        AvatarUploadDto: {
            /**
             * Format: binary
             * @description PNG, JPEG, or WebP avatar up to 2 MB
             */
            avatar: string;
        };
        WsTokenResponseDto: {
            /** @description Short-lived JWT used only for Socket.IO authentication */
            token: string;
        };
        SessionDto: {
            /** @example session-uuid */
            id: string;
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-12T12:00:00.000Z */
            expiresAt: string;
        };
        WorkspaceResponseDto: {
            /** @example workspace-uuid */
            id: string;
            /** @example Product Team */
            name: string;
            isPersonal: boolean;
            isDemoTemplate: boolean;
            isDemoInstance: boolean;
            /** @example 2026-06-25T18:00:00.000Z */
            demoExpiresAt?: string | null;
            /** @example workspace-uuid */
            demoSourceWorkspaceId?: string | null;
            /** @example user-uuid */
            ownerId: string;
            /** @enum {string} */
            currentUserRole: "owner" | "admin" | "member";
            isActive: boolean;
            /** @example 2026-06-25T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-06-25T12:00:00.000Z */
            updatedAt: string;
        };
        CreateWorkspaceDto: {
            /** @example Product Team */
            name: string;
        };
        UserResponseDto: {
            /** @example user-uuid */
            id: string;
            /** @example john@example.com */
            email: string;
            /** @example John Doe */
            name: string;
            /** @example https://example.com/avatar.png */
            avatar?: string;
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-05T12:00:00.000Z */
            updatedAt: string;
        };
        WorkspaceMemberResponseDto: {
            /** @example membership-uuid */
            id: string;
            /** @example user-uuid */
            userId: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
            user: components["schemas"]["UserResponseDto"];
            /** @example 2026-06-25T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-06-25T12:00:00.000Z */
            updatedAt: string;
        };
        UpdateWorkspaceMemberRoleDto: {
            /** @enum {string} */
            role: "admin" | "member";
        };
        CreateWorkspaceInviteDto: {
            /**
             * @default member
             * @enum {string}
             */
            defaultRole: "member" | "admin";
            /** @default 7 */
            expiresInDays: number;
            maxUses?: number | null;
            allowedEmail?: string | null;
            /** @example example.com */
            allowedEmailDomain?: string | null;
        };
        CreatedWorkspaceInviteResponseDto: {
            id: string;
            workspaceId: string;
            /** @enum {string} */
            defaultRole: "owner" | "admin" | "member";
            createdById: string;
            createdByName: string;
            /** Format: date-time */
            expiresAt: string;
            maxUses: number | null;
            usesCount: number;
            /** Format: date-time */
            revokedAt: string | null;
            allowedEmailDomain: string | null;
            hasSpecificEmailRestriction: boolean;
            /** Format: date-time */
            createdAt: string;
            /** @description Raw token returned only once when the invite is created */
            token: string;
        };
        WorkspaceInviteResponseDto: {
            id: string;
            workspaceId: string;
            /** @enum {string} */
            defaultRole: "owner" | "admin" | "member";
            createdById: string;
            createdByName: string;
            /** Format: date-time */
            expiresAt: string;
            maxUses: number | null;
            usesCount: number;
            /** Format: date-time */
            revokedAt: string | null;
            allowedEmailDomain: string | null;
            hasSpecificEmailRestriction: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        WorkspaceInvitePreviewDto: {
            workspaceId: string;
            workspaceName: string;
            inviterName: string;
            /** Format: date-time */
            expiresAt: string;
            /** @enum {string} */
            defaultRole: "owner" | "admin" | "member";
            emailRestricted: boolean;
            isDemoInvite: boolean;
        };
        BoardCapabilitiesResponseDto: {
            canReadBoard: boolean;
            canEditBoardContent: boolean;
            canManageBoardMembers: boolean;
            canDeleteBoard: boolean;
            canManageColumns: boolean;
            canUseWhiteboard: boolean;
            canManageBoardSettings: boolean;
        };
        TeamSummaryResponseDto: {
            /** @example team-uuid */
            id: string;
            /** @example Design */
            name: string;
            /** @example #8b5cf6 */
            color: string;
            /** @example workspace-uuid */
            workspaceId: string;
        };
        TaskResponseDto: {
            /** @example task-uuid */
            id: string;
            /** @example Task 1 */
            title: string;
            description?: string;
            /**
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /** @example 0 */
            order: number;
            /**
             * @example [
             *       "Label 1",
             *       "Label 2"
             *     ]
             */
            labels?: string[];
            /** @example 2026-05-05T12:00:00.000Z */
            dueDate?: string;
            /** @example assignee-user-uuid */
            assigneeId?: string;
            assigneeName?: string;
            assignee?: components["schemas"]["UserResponseDto"];
            /** @example team-uuid */
            teamId?: string | null;
            team?: components["schemas"]["TeamSummaryResponseDto"] | null;
            isCompleted?: boolean;
            /** @example 2026-05-05T12:00:00.000Z */
            completedAt?: string;
            /** @example column-uuid */
            columnId: string;
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-05T12:00:00.000Z */
            updatedAt: string;
        };
        ColumnResponseDto: {
            /** @example column-uuid */
            id: string;
            /** @example To Do */
            title: string;
            /** @example 0 */
            order: number;
            /** @example board-uuid */
            boardId: string;
            tasks?: components["schemas"]["TaskResponseDto"][];
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-05T12:00:00.000Z */
            updatedAt: string;
        };
        BoardMemberResponseDto: {
            /** @example member-uuid */
            id: string | null;
            /** @example user-uuid */
            userId: string;
            user: components["schemas"]["UserResponseDto"];
            /** @enum {string} */
            role: "owner" | "editor" | "viewer";
            /** @example user-uuid */
            invitedById: string | null;
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-05T12:00:00.000Z */
            updatedAt: string;
        };
        BoardResponseDto: {
            /** @example board-uuid */
            id: string;
            /** @example Board 1 */
            title: string;
            /** @example Board 1 description */
            description?: string;
            /** @example #669266 */
            color?: string;
            /** @example user-uuid */
            ownerId: string;
            /** @example workspace-uuid */
            workspaceId: string;
            /** @enum {string} */
            currentUserRole: "owner" | "editor" | "viewer";
            capabilities: components["schemas"]["BoardCapabilitiesResponseDto"];
            columns?: components["schemas"]["ColumnResponseDto"][];
            members?: components["schemas"]["BoardMemberResponseDto"][];
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-05T12:00:00.000Z */
            updatedAt: string;
        };
        BoardViewResponseDto: {
            /** @example view-uuid */
            id: string;
            /** @example My urgent tasks */
            title: string;
            /** @example board-uuid */
            boardId: string;
            /** @example user-uuid */
            ownerId: string;
            /**
             * @example {
             *       "assignee": "me",
             *       "priority": "urgent"
             *     }
             */
            filters: Record<string, never>;
            /**
             * @example {
             *       "sort": "priority"
             *     }
             */
            sort: Record<string, never>;
            isDefault: boolean;
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-05T12:00:00.000Z */
            updatedAt: string;
        };
        CreateBoardViewDto: {
            /** @example My urgent tasks */
            title: string;
            /**
             * @example {
             *       "assignee": "me",
             *       "priority": "urgent"
             *     }
             */
            filters?: Record<string, never>;
            /**
             * @example {
             *       "sort": "priority"
             *     }
             */
            sort?: Record<string, never>;
            /** @default false */
            isDefault: boolean;
        };
        UpdateBoardViewDto: {
            /** @example My urgent tasks */
            title?: string;
            /**
             * @example {
             *       "assignee": "me",
             *       "priority": "urgent"
             *     }
             */
            filters?: Record<string, never>;
            /**
             * @example {
             *       "sort": "priority"
             *     }
             */
            sort?: Record<string, never>;
            /** @default false */
            isDefault: boolean;
        };
        ShareBoardDto: {
            /** @description ID пользователя для приглашения */
            userId?: string;
            /** @description Email пользователя для приглашения */
            email?: string;
            /**
             * @default editor
             * @enum {string}
             */
            role: "editor" | "viewer";
        };
        UpdateBoardMemberRoleDto: {
            /** @enum {string} */
            role: "editor" | "viewer";
        };
        CreateBoardDto: {
            /** @example Board 1 */
            title: string;
            /** @example Board 1 description */
            description?: string;
            /** @example #669266 */
            color?: string;
            /**
             * @default empty
             * @enum {string}
             */
            template: "empty" | "scrum";
            /** @example workspace-uuid */
            workspaceId?: string;
        };
        UpdateBoardDto: {
            /** @example Board 1 */
            title?: string;
            /** @example Board 1 description */
            description?: string;
            /** @example #669266 */
            color?: string;
        };
        TeamMemberResponseDto: {
            /** @example team-membership-uuid */
            id: string;
            /** @example team-uuid */
            teamId: string;
            /** @example user-uuid */
            userId: string;
            user: components["schemas"]["UserResponseDto"];
            /** @example 2026-06-25T12:00:00.000Z */
            createdAt: string;
        };
        TeamResponseDto: {
            /** @example team-uuid */
            id: string;
            /** @example Design */
            name: string;
            description?: string | null;
            /** @example #8b5cf6 */
            color: string;
            /** @example workspace-uuid */
            workspaceId: string;
            /** @example user-uuid */
            createdById: string | null;
            members: components["schemas"]["TeamMemberResponseDto"][];
            /** @example 2026-06-25T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-06-25T12:00:00.000Z */
            updatedAt: string;
        };
        CreateTeamDto: {
            /** @example Design */
            name: string;
            /** @example Product design team */
            description?: string;
            /** @example #8b5cf6 */
            color?: string;
        };
        UpdateTeamDto: {
            /** @example Design */
            name?: string;
            /** @example Product design team */
            description?: string;
            /** @example #8b5cf6 */
            color?: string;
        };
        AddTeamMemberDto: {
            /** @example user-uuid */
            userId: string;
        };
        DemoWorkspaceSessionDto: {
            user: components["schemas"]["UserDto"];
            /** @example workspace-uuid */
            workspaceId: string;
            /** @example board-uuid */
            boardId: string;
        };
        CreateColumnDto: {
            /** @example To Do */
            title: string;
            /** @example board-uuid */
            boardId: string;
            /** @example 0 */
            order?: number;
        };
        UpdateColumnDto: {
            /** @example To Do */
            title?: string;
            /** @example board-uuid */
            boardId?: string;
            /** @example 0 */
            order?: number;
        };
        ReorderColumnsDto: {
            /** @description Массив ID колонок в новой последовательности */
            columnIds: string[];
        };
        CreateTaskDto: {
            /** @example Task 1 */
            title: string;
            description?: string;
            /**
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /**
             * @example [
             *       "Label 1",
             *       "Label 2"
             *     ]
             */
            labels?: string[];
            dueDate?: string;
            /** @example assignee-user-uuid */
            assigneeId?: string;
            isCompleted?: boolean;
            /** @example 2026-05-05T12:00:00.000Z */
            completedAt?: string;
            assigneeName?: string;
            /** @example team-uuid */
            teamId?: string | null;
            /** @example column-uuid */
            columnId: string;
            order?: number;
        };
        UpdateTaskDto: {
            /** @example Task 1 */
            title?: string;
            description?: string;
            /**
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /**
             * @example [
             *       "Label 1",
             *       "Label 2"
             *     ]
             */
            labels?: string[];
            dueDate?: string;
            /** @example assignee-user-uuid */
            assigneeId?: string;
            isCompleted?: boolean;
            /** @example 2026-05-05T12:00:00.000Z */
            completedAt?: string;
            assigneeName?: string;
            /** @example team-uuid */
            teamId?: string | null;
            /** @example column-uuid */
            columnId?: string;
            order?: number;
        };
        MoveTaskDto: {
            /** @description ID новой колонки */
            columnId: string;
            /** @description Новая позиция заказа */
            order: number;
        };
        ReorderTasksDto: {
            /** @description Массив тасок в новой последовательности */
            taskIds: string[];
        };
        AnalyticsItemDto: {
            /** @example 2026-05-05 */
            period: string;
            /** @example 12 */
            count: number;
        };
        CompletionSummaryDto: {
            /** @example 24 */
            total: number;
            /** @example 18 */
            onTime: number;
            /** @example 6 */
            late: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["RegisterRequestDto"];
                "application/json": components["schemas"]["RegisterRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_updateAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AvatarUploadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_resetAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_wsToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsTokenResponseDto"];
                };
            };
        };
    };
    AuthController_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"][];
                };
            };
        };
    };
    AuthController_revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StorageController_avatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    WorkspacesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponseDto"][];
                };
            };
        };
    };
    WorkspacesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponseDto"];
                };
            };
        };
    };
    WorkspacesController_switchActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponseDto"];
                };
            };
        };
    };
    WorkspacesController_members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberResponseDto"][];
                };
            };
        };
    };
    WorkspacesController_updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceMemberRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberResponseDto"];
                };
            };
        };
    };
    WorkspacesController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspacesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspaceInvitesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceInviteResponseDto"][];
                };
            };
        };
    };
    WorkspaceInvitesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceInviteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedWorkspaceInviteResponseDto"];
                };
            };
        };
    };
    WorkspaceInvitesController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspaceInvitesController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceInvitePreviewDto"];
                };
            };
        };
    };
    WorkspaceInvitesController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponseDto"];
                };
            };
        };
    };
    BoardsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponseDto"][];
                };
            };
        };
    };
    BoardsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponseDto"];
                };
            };
        };
    };
    BoardsController_checkAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BoardsController_views: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardViewResponseDto"][];
                };
            };
        };
    };
    BoardsController_createView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardViewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardViewResponseDto"];
                };
            };
        };
    };
    BoardsController_deleteView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                viewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BoardsController_updateView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                viewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBoardViewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardViewResponseDto"];
                };
            };
        };
    };
    BoardsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponseDto"];
                };
            };
        };
    };
    BoardsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBoardDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponseDto"];
                };
            };
        };
    };
    BoardsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BoardsController_share: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareBoardDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardMemberResponseDto"];
                };
            };
        };
    };
    BoardsController_members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardMemberResponseDto"][];
                };
            };
        };
    };
    BoardsController_updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBoardMemberRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardMemberResponseDto"];
                };
            };
        };
    };
    BoardsController_revokeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponseDto"][];
                };
            };
        };
    };
    TeamsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponseDto"];
                };
            };
        };
    };
    TeamsController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponseDto"][];
                };
            };
        };
    };
    TeamsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponseDto"];
                };
            };
        };
    };
    TeamsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponseDto"];
                };
            };
        };
    };
    TeamsController_listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberResponseDto"][];
                };
            };
        };
    };
    TeamsController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                teamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTeamMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberResponseDto"];
                };
            };
        };
    };
    TeamsController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                teamId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamsController_listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"][];
                };
            };
        };
    };
    DemoController_demoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoWorkspaceSessionDto"];
                };
            };
        };
    };
    DemoController_resetWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoWorkspaceSessionDto"];
                };
            };
        };
    };
    DemoController_registerFromDemoInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoWorkspaceSessionDto"];
                };
            };
        };
    };
    ColumnsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateColumnDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnResponseDto"];
                };
            };
        };
    };
    ColumnsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateColumnDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnResponseDto"];
                };
            };
        };
    };
    ColumnsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ColumnsController_reorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderColumnsDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_reorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderTasksDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_analyticsDaily: {
        parameters: {
            query?: {
                boardId?: string;
                fromDate?: string;
                toDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsItemDto"][];
                };
            };
        };
    };
    TasksController_analyticsWeekly: {
        parameters: {
            query?: {
                boardId?: string;
                fromDate?: string;
                toDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsItemDto"][];
                };
            };
        };
    };
    TasksController_analyticsMonthly: {
        parameters: {
            query?: {
                boardId?: string;
                fromDate?: string;
                toDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsItemDto"][];
                };
            };
        };
    };
    TasksController_analyticsSummary: {
        parameters: {
            query?: {
                boardId?: string;
                fromDate?: string;
                toDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionSummaryDto"];
                };
            };
        };
    };
}
