/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация пользователя */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Авторизация пользователя */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновление токенов */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход пользователя - удалиение токенов и очищение куки */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение информации о текущем пользователе */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все доски авторизованного пользователя */
        get: operations["BoardsController_findAll"];
        put?: never;
        /** Создать доску */
        post: operations["BoardsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить доску по id */
        get: operations["BoardsController_findOne"];
        /** Обновить доску */
        put: operations["BoardsController_update"];
        post?: never;
        /** Удалить доску */
        delete: operations["BoardsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создание колонки */
        post: operations["ColumnsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/columns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update column title/order */
        put: operations["ColumnsController_update"];
        post?: never;
        /** Delete column (cascades tasks) */
        delete: operations["ColumnsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/columns/board/{boardId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder columns in board */
        put: operations["ColumnsController_reorder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать задачу в колонке */
        post: operations["TasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить задачу */
        put: operations["TasksController_update"];
        post?: never;
        /** Удалить задачу */
        delete: operations["TasksController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Переместить задачу в другую колонку (drag & drop) */
        patch: operations["TasksController_move"];
        trace?: never;
    };
    "/api/tasks/column/{columnId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Переупорядочить задачи в колонке */
        put: operations["TasksController_reorder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example john@example.com */
            email: string;
            /** @example John Doe */
            name: string;
            /** @example password123 */
            password: string;
        };
        UserDto: {
            id: string;
            email: string;
            name: string;
            avatar?: string;
        };
        AuthResponseDto: {
            user: components["schemas"]["UserDto"];
        };
        LoginDto: {
            /** @example john@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        MessageDto: {
            /** @example Успешный ответ */
            message: string;
        };
        TaskResponseDto: {
            /** @example task-uuid */
            id: string;
            /** @example Task 1 */
            title: string;
            description?: string;
            /**
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /** @example 0 */
            order: number;
            /**
             * @example [
             *       "Label 1",
             *       "Label 2"
             *     ]
             */
            labels?: string[];
            /** @example 2026-05-05T12:00:00.000Z */
            dueDate?: string;
            assigneeName?: string;
            /** @example column-uuid */
            columnId: string;
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-05T12:00:00.000Z */
            updatedAt: string;
        };
        ColumnResponseDto: {
            /** @example column-uuid */
            id: string;
            /** @example To Do */
            title: string;
            /** @example 0 */
            order: number;
            /** @example board-uuid */
            boardId: string;
            tasks?: components["schemas"]["TaskResponseDto"][];
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-05T12:00:00.000Z */
            updatedAt: string;
        };
        BoardResponseDto: {
            /** @example board-uuid */
            id: string;
            /** @example Board 1 */
            title: string;
            /** @example Board 1 description */
            description?: string;
            /** @example #6366f1 */
            color?: string;
            /** @example user-uuid */
            ownerId: string;
            columns?: components["schemas"]["ColumnResponseDto"][];
            /** @example 2026-05-05T12:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-05T12:00:00.000Z */
            updatedAt: string;
        };
        CreateBoardDto: {
            /** @example Board 1 */
            title: string;
            /** @example Board 1 description */
            description?: string;
            /** @example #6366f1 */
            color?: string;
        };
        UpdateBoardDto: {
            /** @example Board 1 */
            title?: string;
            /** @example Board 1 description */
            description?: string;
            /** @example #6366f1 */
            color?: string;
        };
        CreateColumnDto: {
            /** @example To Do */
            title: string;
            /** @example board-uuid */
            boardId: string;
            /** @example 0 */
            order?: number;
        };
        UpdateColumnDto: {
            /** @example To Do */
            title?: string;
            /** @example board-uuid */
            boardId?: string;
            /** @example 0 */
            order?: number;
        };
        ReorderColumnsDto: {
            /** @description Массив ID колонок в новой последовательности */
            columnIds: string[];
        };
        CreateTaskDto: {
            /** @example Task 1 */
            title: string;
            description?: string;
            /**
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /**
             * @example [
             *       "Label 1",
             *       "Label 2"
             *     ]
             */
            labels?: string[];
            dueDate?: string;
            assigneeName?: string;
            /** @example column-uuid */
            columnId: string;
            order?: number;
        };
        UpdateTaskDto: {
            /** @example Task 1 */
            title?: string;
            description?: string;
            /**
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /**
             * @example [
             *       "Label 1",
             *       "Label 2"
             *     ]
             */
            labels?: string[];
            dueDate?: string;
            assigneeName?: string;
            /** @example column-uuid */
            columnId?: string;
            order?: number;
        };
        MoveTaskDto: {
            /** @description ID новой колонки */
            columnId: string;
            /** @description Новая позиция заказа */
            order: number;
        };
        ReorderTasksDto: {
            /** @description Массив тасок в новой последовательности */
            taskIds: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    BoardsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponseDto"][];
                };
            };
        };
    };
    BoardsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponseDto"];
                };
            };
        };
    };
    BoardsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponseDto"];
                };
            };
        };
    };
    BoardsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBoardDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponseDto"];
                };
            };
        };
    };
    BoardsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ColumnsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateColumnDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnResponseDto"];
                };
            };
        };
    };
    ColumnsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateColumnDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnResponseDto"];
                };
            };
        };
    };
    ColumnsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ColumnsController_reorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderColumnsDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_reorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderTasksDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
